[project]
name = "jobfinderai"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "notebook>=7.5.0",
    "pandas>=2.3.3",
    "pandas-stubs==2.3.2.250926",
    "tabulate>=0.9.0",
]
